import type { Property, Agent } from "@/types";

// ─── Mock Agents ──────────────────────────────────────────────────
export const mockAgents: Agent[] = [
  {
    id: "1",
    name: "Alejandro",
    lastName: "García Morales",
    email: "alejandro@elitepropiedades.com",
    phone: "+52 55 1234 5678",
    whatsapp: "+525512345678",
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80",
    bio: "Especialista en propiedades de lujo con más de 12 años en el mercado premium de la CDMX. Ha cerrado transacciones por encima de los $2,500 MDD.",
    specialty: "Residencias de lujo en Polanco y Lomas",
    properties: 47,
    slug: "alejandro-garcia",
    isActive: true,
  },
  {
    id: "2",
    name: "Valentina",
    lastName: "Torres Ríos",
    email: "valentina@elitepropiedades.com",
    phone: "+52 55 9876 5432",
    whatsapp: "+525598765432",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80",
    bio: "Experta en desarrollos inmobiliarios y penthouses en Santa Fe. Formada en arquitectura con especialidad en bienes raíces de lujo.",
    specialty: "Penthouses y desarrollos premium en Santa Fe",
    properties: 38,
    slug: "valentina-torres",
    isActive: true,
  },
  {
    id: "3",
    name: "Rafael",
    lastName: "Mendoza Vega",
    email: "rafael@elitepropiedades.com",
    phone: "+52 55 5555 0000",
    whatsapp: "+525555550000",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    bio: "20 años de trayectoria en el segmento residencial plus. Especializado en Condesa, Roma Norte y Juárez para clientes nacionales e internacionales.",
    specialty: "Residencial plus en Condesa y Roma",
    properties: 62,
    slug: "rafael-mendoza",
    isActive: true,
  },
];

// ─── Shared zone stubs ────────────────────────────────────────────
const zonaPolanco   = { id: "z1", name: "Polanco",             city: "Ciudad de México", state: "CDMX", country: "México", slug: "polanco" };
const zonaSantaFe   = { id: "z2", name: "Santa Fe",            city: "Ciudad de México", state: "CDMX", country: "México", slug: "santa-fe" };
const zonaLomas     = { id: "z3", name: "Lomas de Chapultepec",city: "Ciudad de México", state: "CDMX", country: "México", slug: "lomas-de-chapultepec" };
const zonaCondesa   = { id: "z4", name: "Condesa",             city: "Ciudad de México", state: "CDMX", country: "México", slug: "condesa" };
const zonaRomaNorte = { id: "z5", name: "Roma Norte",          city: "Ciudad de México", state: "CDMX", country: "México", slug: "roma-norte" };

// ─── Mock Properties ──────────────────────────────────────────────
export const mockProperties: Property[] = [
  {
    id: "p1",
    title: "Penthouse Residencial Polanco",
    slug: "penthouse-residencial-polanco",
    description: "Extraordinario penthouse con vistas panorámicas de 360° a la Ciudad de México. Terraza privada de 120 m², acabados de la más alta calidad y amenidades de clase mundial.",
    status: "ACTIVA",
    type: "Penthouse",
    listingType: "VENTA",
    price: 38_500_000,
    currency: "MXN",
    pricePerM2: 101_315,
    zone: zonaPolanco,
    totalArea: 500,
    builtArea: 380,
    bedrooms: 4,
    bathrooms: 4,
    halfBathrooms: 1,
    parkingSpaces: 3,
    images: [
      { id: "i1", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&q=85", alt: "Sala principal", isPrimary: true, order: 0 },
    ],
    features: [],
    agent: mockAgents[0],
    isFeatured: true,
    isNew: false,
    isExclusive: true,
    createdAt: new Date("2026-05-15"),
    updatedAt: new Date("2026-06-01"),
    publishedAt: new Date("2026-05-15"),
  },
  {
    id: "p2",
    title: "Casa en Lomas de Chapultepec",
    slug: "casa-lomas-chapultepec",
    description: "Imponente residencia de estilo contemporáneo en uno de los corredores más exclusivos de la ciudad. Jardín privado de 800 m², sala multimedia, spa y caballeriza.",
    status: "ACTIVA",
    type: "Casa",
    listingType: "VENTA",
    price: 72_000_000,
    currency: "MXN",
    zone: zonaLomas,
    totalArea: 1_800,
    builtArea: 950,
    landArea: 850,
    bedrooms: 6,
    bathrooms: 6,
    halfBathrooms: 2,
    parkingSpaces: 5,
    images: [
      { id: "i2", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=85", alt: "Fachada residencia", isPrimary: true, order: 0 },
    ],
    features: [],
    agent: mockAgents[0],
    isFeatured: true,
    isNew: false,
    isExclusive: true,
    createdAt: new Date("2026-04-10"),
    updatedAt: new Date("2026-05-20"),
    publishedAt: new Date("2026-04-10"),
  },
  {
    id: "p3",
    title: "Departamento Premium Santa Fe",
    slug: "departamento-premium-santa-fe",
    description: "Moderno departamento en torre insignia de Santa Fe con vistas a Bosque de las Lomas. Doble altura en sala, cocina Boffi y amenidades ejecutivas de primer nivel.",
    status: "ACTIVA",
    type: "Departamento",
    listingType: "VENTA",
    price: 18_900_000,
    currency: "MXN",
    zone: zonaSantaFe,
    totalArea: 280,
    builtArea: 240,
    bedrooms: 3,
    bathrooms: 3,
    halfBathrooms: 1,
    parkingSpaces: 2,
    images: [
      { id: "i3", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=85", alt: "Interior departamento", isPrimary: true, order: 0 },
    ],
    features: [],
    agent: mockAgents[1],
    isFeatured: true,
    isNew: true,
    isExclusive: false,
    createdAt: new Date("2026-06-01"),
    updatedAt: new Date("2026-06-10"),
    publishedAt: new Date("2026-06-01"),
  },
  {
    id: "p4",
    title: "Villa Residencial Condesa",
    slug: "villa-residencial-condesa",
    description: "Espectacular villa de diseño en el corazón de Condesa. Patio interior con jardín tropical, roof garden con alberca infinita y estudio-biblioteca de doble altura.",
    status: "ACTIVA",
    type: "Villa",
    listingType: "RENTA",
    price: 195_000,
    currency: "MXN",
    zone: zonaCondesa,
    totalArea: 650,
    builtArea: 480,
    bedrooms: 5,
    bathrooms: 5,
    halfBathrooms: 1,
    parkingSpaces: 3,
    images: [
      { id: "i4", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=85", alt: "Fachada villa", isPrimary: true, order: 0 },
    ],
    features: [],
    agent: mockAgents[2],
    isFeatured: true,
    isNew: false,
    isExclusive: false,
    createdAt: new Date("2026-03-20"),
    updatedAt: new Date("2026-06-05"),
    publishedAt: new Date("2026-03-20"),
  },
  {
    id: "p5",
    title: "Suite de Lujo en Polanco",
    slug: "suite-lujo-polanco",
    description: "Elegante suite con vista al Bosque de Chapultepec. Acabados en mármol travertino, cocina European Kitchen y clóset vestidor walk-in de diseño. Edificio boutique con solo 12 unidades.",
    status: "ACTIVA",
    type: "Departamento",
    listingType: "RENTA",
    price: 65_000,
    currency: "MXN",
    zone: zonaPolanco,
    totalArea: 160,
    builtArea: 145,
    bedrooms: 2,
    bathrooms: 2,
    halfBathrooms: 0,
    parkingSpaces: 1,
    images: [
      { id: "i5", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=85", alt: "Suite interior", isPrimary: true, order: 0 },
    ],
    features: [],
    agent: mockAgents[0],
    isFeatured: false,
    isNew: true,
    isExclusive: true,
    createdAt: new Date("2026-06-10"),
    updatedAt: new Date("2026-06-15"),
    publishedAt: new Date("2026-06-10"),
  },
  {
    id: "p6",
    title: "Residencia Art Déco Roma Norte",
    slug: "residencia-art-deco-roma-norte",
    description: "Joya arquitectónica de los años 30 completamente restaurada con criterios de lujo contemporáneo. Patio central con fuente original, vitrales y pisos de duela de madera maciza.",
    status: "ACTIVA",
    type: "Casa",
    listingType: "VENTA",
    price: 28_500_000,
    currency: "MXN",
    zone: zonaRomaNorte,
    totalArea: 520,
    builtArea: 420,
    landArea: 100,
    bedrooms: 4,
    bathrooms: 3,
    halfBathrooms: 1,
    parkingSpaces: 2,
    images: [
      { id: "i6", url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=900&q=85", alt: "Fachada art déco", isPrimary: true, order: 0 },
    ],
    features: [],
    agent: mockAgents[2],
    isFeatured: true,
    isNew: false,
    isExclusive: false,
    createdAt: new Date("2026-02-14"),
    updatedAt: new Date("2026-05-10"),
    publishedAt: new Date("2026-02-14"),
  },
];

export const mockFeaturedProperties = mockProperties.filter((p) => p.isFeatured).slice(0, 6);
